name: Create commit status check
inputs:
  sha:
    type: string
    required: true
  state:
    type: string
    required: true
  context:
    type: string
    required: true
  description:
    type: string
    required: false
runs:
  using: composite
  steps:
    - name: Create commit status check
      run: gh api /repos/${{github.repository}}/statuses/${{inputs.sha}} -X POST -f state=${{inputs.state}} -f description='${{inputs.description}}' -f context='${{inputs.context}}'
      env:
        GITHUB_TOKEN: ${{github.token}}
