name: Create Pull Request
on:
  workflow_call:
    inputs:
      base:
        type: string
        required: true
      head:
        type: string
        required: true
permissions: write-all
env:
  DEFAULT_PR_TITLE: "build(#): PR automático // ${{inputs.head}} > ${{inputs.base}}"
jobs:
  create-pr:
    name: Create PR to ${{inputs.base}}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PRECUSORA_DEFAULT_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check if PR exists
        id: pr-number
        run: echo "number=$(gh api "repos/${{github.repository}}/pulls?base=${{inputs.base}}&head=${{github.repository_owner}}:${{inputs.head}}&state=open" --jq ".[].number")" >> $GITHUB_OUTPUT
      - name: Edit PR to ${{inputs.base}}
        if: steps.pr-number.outputs.number != ''
        run: gh api repos/${{github.repository}}/pulls/${{steps.pr-number.outputs.number}} -X PATCH -f title="${{env.DEFAULT_PR_TITLE}}"
      - name: Create PR to ${{inputs.base}}
        if: steps.pr-number.outputs.number == ''
        run: gh api repos/${{github.repository}}/pulls -X POST -f title="${{env.DEFAULT_PR_TITLE}}" -f base="${{inputs.base}}" -f head="${{inputs.head}}"
