name: Deploy to GCP - DEV
on:
  workflow_call:
    outputs:
      deployed: 
        value: ${{jobs.deploy.result == 'success' && 'true' || 'false'}}
      destroyed: 
        value: ${{jobs.destroy.result == 'success' && 'true' || 'false'}}
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/ext-initialization-pipeline-website-properties.yml
  destroy:
    needs: init
    name: Destroy resources
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-destroy-website.yml
    with:
      bucket: ${{needs.init.outputs.deploy-storage-dev}}
      environment: dev
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
  deploy:
    needs: init
    name: Deploy resources
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-gcp-deploy-website.yml
    with:
      path: ${{ needs.init.outputs.deploy-base-path }}
      resource-directory: ${{ needs.init.outputs.deploy-resource-directory }}
      bucket: ${{ needs.init.outputs.deploy-bucket-dev }}
      environment: dev
      node-version: ${{needs.init.outputs.runner-version}}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      token: ${{ secrets.GH_DEFAULT_ORG_PAT }}
  finish-deploy:
    name: Finish deploy
    needs:
      - deploy
      - destroy
    if: always() && (needs.deploy.result == 'success' || needs.destroy.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
