name: Create commit status check
on:
  workflow_call:
    inputs:
      sha:
        type: string
        required: true
      state:
        type: string
        required: true
      context:
        type: string
        required: true
      description:
        type: string
        required: false
    secrets:
      token:
        required: false
jobs:
  create-commit-status-check:
    name: Create commit status check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create commit status check
        run: gh api /repos/${{github.repository}}/statuses/${{inputs.sha}} -X POST -f state='${{inputs.state}}' -f description='${{inputs.description}}' -f context='${{inputs.context}}'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN || github.token}}
