name: Deploy to GCP - DEV
on:
  workflow_call:
    outputs:
      deployed: 
        value: ${{jobs.deploy.result == 'success' && 'true' || 'false'}}
      destroyed: 
        value: ${{jobs.destroy.result == 'success' && 'true' || 'false'}}
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-initialization-pipeline-website-properties.yml@main
  destroy-infra:
    needs: init
    name: Destroy infrastructure
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-terraform-destroy.yml
    with:
      environment: dev
      destroy: "true"
      path: infra
    secrets: inherit
  deploy-infra:
    needs: init
    if: needs.init.outputs.destroy == 'false'
    name: Deploy infrastructure
    uses: ./.github/workflows/ext-gcp-terraform-deploy.yml
    with:
      environment: dev
      path: infra
    secrets: inherit
  deploy-app:
    needs:
      - init
      - deploy-infra
    name: Deploy application
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-gcp-deploy-website-firebase-hosting.yml
    with:
      path: ${{ needs.init.outputs.deploy-base-path }}
      environment: dev
      node-version: ${{needs.init.outputs.runner-version}}
    secrets: inherit
  finish-deploy:
    name: Finish deploy
    needs:
      - deploy-app
      - destroy-infra
    if: always() && (needs.deploy-app.result == 'success' || needs.destroy-infra.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
