name: Deploy to environment
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      resource-directory:
        required: true
        type: string
      site-id:
        required: true
        type: string
      environment:
        required: true
        type: string
      node-version:
        type: string
        default: 18.x
    secrets:
      project-name:
        required: true
      token:
        required: true
      fb-token:
        required: true
env:
  PROJECT_NAME: ${{ secrets.project-name }}-${{ inputs.environment }}
  ENVIRONMENT: ${{ inputs.environment == 'dev' && 'DEV' || inputs.environment == 'prod' && 'PROD' }}
permissions: write-all
jobs:
  deploy:
    name: Deploy application
    environment: ${{ inputs.environment == 'dev' && 'DEV' || inputs.environment == 'prod' && 'PROD' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node ${{inputs.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          registry-url: https://npm.pkg.github.com
      - name: Prepare environment
        run: cp environments/${{env.ENVIRONMENT}}.env .env
        working-directory: ${{inputs.path}}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT }}
        working-directory: ${{inputs.path}}
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Build
        run: npm run build
        working-directory: ${{inputs.path}}
      - name: Deploy
        run: |
          firebase use ${{ env.PROJECT_NAME }}
          firebase deploy --only hosting:app
        working-directory: ${{inputs.path}}
        env:
          FIREBASE_TOKEN: ${{secrets.fb-token}}
