name: Deploy to GCP - DEV
on:
  workflow_call:
    outputs:
      deployed: 
        value: ${{jobs.custom-command.result == 'success' && 'true' || 'false'}}
      destroyed: 
        value: ${{jobs.destroy.result == 'success' && 'true' || 'false'}}
      integration-tests-base-path:
        value: ${{jobs.init.outputs.integration-tests-base-path}}
      integration-tests-report-file:
        value: ${{jobs.init.outputs.integration-tests-report-file}}
      integration-tests-report-format:
        value: ${{jobs.init.outputs.integration-tests-report-format}}
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/ext-initialization-pipeline-properties.yml
  destroy:
    needs: init
    name: Destroy resources
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-destroy-service.yml
    with:
      environment: dev
      region: ${{ needs.init.outputs.region }}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
  settings:
    needs: init
    name: Load application settings
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-load-application-settings.yml
    with:
      environment: dev
  deploy:
    needs:
      - init
      - settings
    name: Deploy resources
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-gcp-deploy-service.yml
    with:
      environment: dev
      region: ${{ needs.init.outputs.region }}
      scaling-memory: ${{ needs.settings.outputs.scaling-memory }}
      scaling-min-instances: ${{ needs.settings.outputs.scaling-min-instances }}
      scaling-max-instances: ${{ needs.settings.outputs.scaling-max-instances }}
      port: ${{ needs.settings.outputs.port }}
      scaling-timeout: ${{ needs.settings.outputs.scaling-timeout }}
      execution-environment: ${{ needs.settings.outputs.execution-environment }}
      ingress: ${{ needs.settings.outputs.ingress }}
      scaling-cpu: ${{ needs.settings.outputs.scaling-cpu }}
      scaling-concurrency: ${{ needs.settings.outputs.scaling-concurrency }}
      cpu-throttling: ${{ needs.settings.outputs.cpu-throttling }}
      service-account: ${{ needs.settings.outputs.service-account }}
      instances: ${{ needs.settings.outputs.instances }}
      env-vars-file: ${{ needs.settings.outputs.env-vars-file }}
      registry: us-docker.pkg.dev
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
      token: ${{ secrets.GH_PRECURSORA_DEFAULT_PAT }}
  custom-command:
    needs: 
      - settings
      - deploy
    name: Custom command
    if: always() && needs.deploy.result == 'success'
    uses: ./.github/workflows/ext-gcp-execute-job-custom-command.yml
    with:
      command-entrypoint: ${{ needs.settings.outputs.command-entrypoint }}
      command-args: ${{ needs.settings.outputs.command-args }}
      region: ${{ needs.deploy.outputs.region }}
      instances: ${{ needs.settings.outputs.instances }}
      service-account: ${{ needs.settings.outputs.service-account }}
      registry: us-docker.pkg.dev
      environment: dev
      env-vars-file: ${{ needs.settings.outputs.env-vars-file }}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
  finish-deploy:
    name: Finish deploy
    needs:
      - custom-command
      - destroy
    if: always() && (needs.custom-command.result == 'success' || needs.destroy.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
