name: Deploy to GCP - PROD
on:
  workflow_call:
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/ext-initialization-pipeline-website-properties.yml
  destroy-infra:
    needs: init
    name: Destroy infrastructure
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-terraform-destroy.yml
    with:
      environment: prod
      destroy: "true"
      path: infra
    secrets: inherit
  deploy-infra:
    needs: init
    if: needs.init.outputs.destroy == 'false'
    name: Deploy infrastructure
    uses: ./.github/workflows/ext-gcp-terraform-deploy.yml
    with:
      environment: prod
      path: infra
    secrets: inherit
  deploy-app:
    needs:
      - init
      - deploy-infra
    name: Deploy application
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-gcp-deploy-website-firebase-hosting.yml
    with:
      path: ${{ needs.init.outputs.deploy-base-path }}
      environment: prod
      node-version: ${{needs.init.outputs.runner-version}}
    secrets: inherit
  create-tag:
    needs: deploy-app
    if: always() && needs.deploy-app.result == 'success'
    name: Create tag
    uses: ./.github/workflows/ext-create-tag.yml
    secrets: inherit
  finish-deploy:
    name: Finish deploy
    needs:
      - create-tag
      - destroy-infra
    if: always() && (needs.create-tag.result == 'success' || needs.destroy-infra.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
