name: Mutation tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
    secrets:
      token:
        required: false
jobs:
  mutation-tests:
    name: Mutation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Run mutation tests
        run: |
          mvn -B pitest:mutationCoverage -f ${{inputs.path}}pom.xml -s ${{inputs.path}}settings.xml \
              -Dserver.github.username=${{ github.repository_owner }} \
              -Dserver.github.password=${{ secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT }}
