name: Execute integration tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      report-file:
        type: string
        required: true
      report-format:
        type: string
        required: true
jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --no-progress
        working-directory: ${{inputs.path}}
      - name: Execute
        id: run
        run: |
          startTime=$(date +%s)

          XDEBUG_MODE="coverage" composer run test-unit

          endTime=$(date +%s)
          echo "executionTime="$(($endTime-$startTime)) >> $GITHUB_OUTPUT
        working-directory: ${{inputs.path}}
