name: Destroy resources
on:
  workflow_call:
    secrets:
      project-number:
        required: true
      project-name:
        required: true
      service-name:
        required: true
    inputs:
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  PROJECT_NUMBER: ${{ secrets.project-number }}
  PROJECT_NAME: ${{ secrets.project-name }}-${{ inputs.environment }}
  SERVICE_NAME: ${{ secrets.service-name }}-${{ inputs.environment }}
permissions: write-all
jobs:
  destroy:
    name: Destroy resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'dev' && 'DEV' || inputs.environment == 'prod' && 'PROD' }}
    steps:
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: devops-app@${{ env.PROJECT_NAME }}.iam.gserviceaccount.com
      - name: Check if job exists
        id: job-status
        run: echo "status="$(gcloud run jobs describe ${{ env.SERVICE_NAME }} --region ${{ inputs.region }} --format 'value(status.conditions[0].status)') >> $GITHUB_OUTPUT
      - name: Destroy job
        if: ${{ steps.job-status.outputs.status == 'True' }}
        run: gcloud run jobs delete ${{ env.SERVICE_NAME }} --region ${{ inputs.region }} --quiet
      - name: Check if service exists
        id: service-status
        run: echo "status="$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ inputs.region }} --format 'value(status.conditions[0].status)') >> $GITHUB_OUTPUT
      - name: Destroy service
        if: ${{ steps.service-status.outputs.status == 'True' }}
        run: gcloud run services delete ${{ env.SERVICE_NAME }} --region ${{ inputs.region }} --quiet
