name: Execute integration tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      report-file:
        type: string
        required: true
      report-format:
        type: string
        required: true
jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Execute
        run: mvn -B clean install -f pom.xml -s settings.xml
        working-directory: ${{inputs.path}}
