name: Create tag
on:
  workflow_call: 
jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Generate App Token
      uses: actions/create-github-app-token@v1
      id: generate-app-token
      with:
          app-id: ${{secrets.GH_APP_ID}}
          private-key: ${{secrets.GH_APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ steps.generate-app-token.outputs.token }}
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag.outputs.new_tag }}
        name: Release ${{ steps.tag.outputs.new_tag }}
        body: ${{ steps.tag.outputs.changelog }}
