name: Unit tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
      report-index-file:
        type: string
        required: false
        default: reports/unit/index.xml
      report-junit-file:
        type: string
        required: false
        default: reports/unit/junit.xml
      minimum-coverage:
        type: number
        required: true
      sha:
        type: string
        required: true
    outputs:
      indexes:
        value: ${{jobs.unit-tests.outputs.indexes}}
    secrets:
      token:
        required: false
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    outputs:
      indexes: ${{steps.export.outputs.indexes}}
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          COMPOSER_AUTH="{\"github-oauth\":{\"github.com\":\"${{secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT}}\"}}" \
          composer install --no-progress
        working-directory: ${{inputs.path}}
      - name: Run tests
        id: run
        continue-on-error: true
        run: |
          startTime=$(date +%s)

          XDEBUG_MODE="coverage" composer run test-unit

          endTime=$(date +%s)
          echo "executionTime="$(($endTime-$startTime)) >> $GITHUB_OUTPUT
        working-directory: ${{inputs.path}}
      - name: Export indexes
        id: export
        run: |
          index=${{inputs.report-index-file}}
          junit=${{inputs.report-junit-file}}

          if [[ -e "${index}" ]]; then
            error=$(grep -Eom 1 'failures="[0-9\.]{1,}|errors="[0-9\.]{1,}' ${junit} | cut -d'"' -f2 | awk '{s+=$1} END {print s}')
            skipped=$(grep -Eom 1 'skipped="[0-9\.]{1,}' ${junit} | cut -d'"' -f2)
            coverage=$(grep -Eo 'percent="[0-9\.]{1,}' ${index} | cut -d'"' -f2 | paste -sd ";" | cut -d';' -f1)
            total=$(grep -Eo 'executable="[0-9\.]{1,}' ${index} | cut -d'"' -f2 | paste -sd ";" | cut -d';' -f1)
            success=$(grep -Eo 'executed="[0-9\.]{1,}' ${index} | cut -d'"' -f2 | paste -sd ";" | cut -d';' -f1)
            noCoverage=$(($total-$success))
            executionTime=${{steps.run.outputs.executionTime}}

            if [ ! -e $junit ]; then
              error=0
              skipped=0
              executionTime=0
            fi
          else
            error=0
            skipped=0
            executionTime=0
            coverage=0
            noCoverage=0
            success=0
          fi

          echo 'indexes={"minimum_coverage":"${{inputs.minimum-coverage}}","coverage":"'${coverage}'","success":"'${success}'","error":"'${error}'","no_coverage":"'${noCoverage}'","skipped":"'${skipped}'","execution_time":"'${executionTime}'"}' >> $GITHUB_OUTPUT
          echo 'coverage='${coverage} >> $GITHUB_OUTPUT
          echo 'description=Minimum: ${{inputs.minimum-coverage}}% • Covered: '${coverage}'% • Success: '${success}' • Error: '${error}' • Skipped: '${skipped}' • Uncovered: '${noCoverage} >> $GITHUB_OUTPUT
        working-directory: ${{inputs.path}}
      - name: Validate coverage
        run: |
          state=failure
          
          if (( ${{steps.export.outputs.coverage}} < ${{inputs.minimum-coverage}} )); then
            echo "#### ❌ Cobertura mínima de ${{inputs.minimum-coverage}}% não atingida" >> $GITHUB_STEP_SUMMARY
          else
            state=success
            echo "#### ✅ Cobertura mínima de ${{inputs.minimum-coverage}}% atingida" >> $GITHUB_STEP_SUMMARY
          fi

          gh api /repos/${{github.repository}}/statuses/${{inputs.sha}} -X POST -f state=${state} -f description='${{steps.export.outputs.description}}' -f context='Unit tests result'

          if (( ${{steps.export.outputs.coverage}} < ${{inputs.minimum-coverage}} )); then
            exit 1;
          fi
        env:
          GH_TOKEN: ${{secrets.token || github.token}}
