name: Validation
on:
  workflow_call:
    inputs:
      path:
        type: string
        default: ./
permissions: write-all
jobs:
  validation:
    name: Validate infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform format check
        run: terraform fmt -check
        working-directory: ${{ inputs.path }}
      - name: Terraform init
        run: terraform init
        working-directory: ${{ inputs.path }}
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ inputs.path }}
