name: Mutation tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
      report-index-file:
        type: string
        required: false
        default: target/pit-reports/index.html
      minimum-coverage:
        type: string
        required: true
      sha:
        type: string
        required: true
    outputs:
      indexes:
        value: ${{jobs.mutation-tests.outputs.indexes}}
    secrets:
      token:
        required: false
jobs:
  mutation-tests:
    name: Mutation tests
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      indexes: ${{steps.export.outputs.indexes}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Run tests
        continue-on-error: true
        id: run
        run: |
          echo "startTime="$(date +%s) >> $GITHUB_OUTPUT
          mvn -B clean install -f pom.xml -s settings.xml \
              -Dserver.github.username=${{ github.repository_owner }} \
              -Dserver.github.password=${{ secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT }}
        working-directory: ${{inputs.path}}
      - name: Generate reports
        run: |
          mvn -B pitest:mutationCoverage -f pom.xml -s settings.xml \
              -DfailWhenNoMutations=false \
              -DtimestampedReports=false
        working-directory: ${{inputs.path}}
      - name: Export indexes
        id: export
        run: |
          executionTime=$(($(date +%s)-${{steps.run.outputs.startTime}}))
          index=${{inputs.report-index-file}}

          if [[ -e "${index}" ]]; then
            coverage=$(grep -Eo 'td>[^>]*%' ${index} | paste -sd ' ' | cut -d'%' -f2 | cut -d'>' -f2)
            success=$(grep -Eo 'td>[^>]*%.?*>[0-9]{1,}/[0-9]{1,}' ${index} | cut -d'/' -f2 | paste -sd ',' | cut -d'>' -f5 | cut -d',' -f1)
            total=$(grep -Eo 'td>[^>]*%.?*>[0-9]{1,}/[0-9]{1,}' ${index} | cut -d'/' -f3 | paste -sd ',' | cut -d',' -f2)
            noCoverage=$(($total-$success))

            if [[ $total == 0 ]]; then
              coverage=100
              noCoverage=0
              success=0
            fi
          else
            coverage=0
            noCoverage=0
            success=0
          fi

          echo 'indexes={"minimum_coverage":"${{inputs.minimum-coverage}}","coverage":"'${coverage}'","success":"'${success}'","error":"0","no_coverage":"'${noCoverage}'","skipped":"0","execution_time":"'${executionTime}'"}' >> $GITHUB_OUTPUT
          echo 'coverage='${coverage} >> $GITHUB_OUTPUT
          echo 'description=Minimum: ${{inputs.minimum-coverage}}% • Covered: '${coverage}'% • Success: '${success}' • Uncovered: '${noCoverage} >> $GITHUB_OUTPUT
        working-directory: ${{inputs.path}}
      - name: Validate coverage
        run: |
          state=failure

          if [[ $(awk '{print($1 < $2)}' <<< "${{steps.export.outputs.coverage}} ${{inputs.minimum-coverage}}") == 1 ]]; then
            echo "#### ❌ Cobertura mínima de ${{inputs.minimum-coverage}}% não atingida" >> $GITHUB_STEP_SUMMARY
          else
            state=success
            echo "#### ✅ Cobertura mínima de ${{inputs.minimum-coverage}}% atingida" >> $GITHUB_STEP_SUMMARY
          fi

          gh api /repos/${{github.repository}}/statuses/${{inputs.sha}} -X POST -f state=${state} -f description='${{steps.export.outputs.description}}' -f context='Mutation tests result'

          if [[ $(awk '{print($1 < $2)}' <<< "${{steps.export.outputs.coverage}} ${{inputs.minimum-coverage}}") == 1 ]]; then
            exit 1;
          fi
        env:
          GH_TOKEN: ${{secrets.token || github.token}}
