name: Create Pull Request
on:
  workflow_call:
    inputs:
      base:
        type: string
        required: true
      head:
        type: string
        required: true
      labels:
        type: string
        required: false
permissions: write-all
env:
  DEFAULT_PR_TITLE: "build(#): PR automático // ${{inputs.head}} > ${{inputs.base}}"
jobs:
  create-pr:
    name: Create PR to ${{inputs.base}}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{github.token}}
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{secrets.GH_APP_ID}}
          private-key: ${{secrets.GH_APP_PRIVATE_KEY}}
          owner: ${{ github.repository_owner }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check if PR exists
        id: pr-number
        run: echo "number=$(gh api "repos/${{github.repository}}/pulls?base=${{inputs.base}}&head=${{github.repository_owner}}:${{inputs.head}}&state=open" --jq ".[].number")" >> $GITHUB_OUTPUT
      - name: Edit PR to ${{inputs.base}}
        if: steps.pr-number.outputs.number != ''
        run: gh api repos/${{github.repository}}/pulls/${{steps.pr-number.outputs.number}} -X PATCH -f title="${{env.DEFAULT_PR_TITLE}}"
        env:
          GH_TOKEN: ${{steps.generate-app-token.outputs.token}}
      - name: Create PR to ${{inputs.base}}
        if: steps.pr-number.outputs.number == ''
        id: pr-creation
        run: echo "number=$(gh api repos/${{github.repository}}/pulls -X POST -f title="${{env.DEFAULT_PR_TITLE}}" -f base="${{inputs.base}}" -f head="${{inputs.head}}" --jq ".number")" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{steps.generate-app-token.outputs.token}}
      - name: Assignee PR and Add Labels
        run: gh pr edit ${{steps.pr-number.outputs.number || steps.pr-creation.outputs.number}} --repo ${{github.repository}} --add-assignee="${{github.actor}}" --add-label="${{inputs.labels}}"
        env:
          GH_TOKEN: ${{steps.generate-app-token.outputs.token}}
          GITHUB_TOKEN: ${{steps.generate-app-token.outputs.token}}
