name: Mutation tests
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
      report-index-file:
        type: string
        required: false
        default: target/pit-reports/index.html
    outputs:
      indexes:
        value: ${{jobs.mutation-tests.outputs.indexes}}
    secrets:
      token:
        required: false
jobs:
  mutation-tests:
    name: Mutation
    runs-on: ubuntu-latest
    outputs:
      indexes: ${{steps.export.outputs.indexes}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Run mutation tests
        continue-on-error: true
        run: |
          mvn -B pitest:mutationCoverage -f ${{ inputs.path }}pom.xml -s ${{ inputs.path }}settings.xml \
              -Dserver.github.username=${{ github.repository_owner }} \
              -Dserver.github.password=${{ secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT }} \
              -DfailWhenNoMutations=false \
              -DtimestampedReports=false
      - name: Export indexes
        id: export
        run: |
          index=${{inputs.path}}${{inputs.report-index-file}}

          if [[ -e "${index}" ]]; then
            coverage=$(grep -Eo 'td>[^>]*%' ${index} | paste -sd ' ' | cut -d'%' -f2 | cut -d'>' -f2)
            noCoverage=$(grep -Eo 'td>[^>]*%.?*>[0-9]*/[0-9]*' ${index} | cut -d'/' -f2 | paste -sd '' | cut -d'>' -f5)
            total=$(grep -Eo 'td>[^>]*%.?*>[0-9]*/[0-9]*' ${index} | cut -d'/' -f3 | paste -sd ',' | cut -d',' -f2)
            success=$(($total-$noCoverage))
            executionTime=0
            error=0

            if [[ $total == 0 ]]; then
              coverage=0
              noCoverage=0
              success=0
              total=0
            fi
          else
            coverage=0
            noCoverage=0
            total=0
            success=0
            executionTime=0
            error=0
          fi

          echo 'indexes={"coverage":"'${coverage}'","success":"'${success}'","error":"'${error}'","no_coverage":"'${noCoverage}'","skipped":"0","execution_time":"'${executionTime}'"}' >> $GITHUB_OUTPUT
