name: Deploy to GCP - PROD
on:
  workflow_call:
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-initialization-pipeline-website-properties.yml@main
  destroy:
    needs: init
    name: Destroy resources
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-destroy-website.yml
    with:
      bucket: ${{needs.init.outputs.deploy-storage-prod}}
      environment: prod
    secrets: inherit
  deploy:
    needs: init
    name: Deploy resources
    if: needs.init.outputs.destroy == 'false'
    uses: ./.github/workflows/ext-gcp-deploy-website.yml
    with:
      path: ${{ needs.init.outputs.deploy-base-path }}
      resource-directory: ${{ needs.init.outputs.deploy-resource-directory }}
      bucket: ${{ needs.init.outputs.deploy-bucket-prod }}
      environment: prod
      node-version: ${{needs.init.outputs.runner-version}}
    secrets: inherit
  create-tag:
    needs: deploy
    if: always() && needs.deploy == 'success'
    name: Create tag
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-tag.yml@main
    secrets: inherit
  finish-deploy:
    name: Finish deploy
    needs:
      - create-tag
      - destroy
    if: always() && (needs.create-tag.result == 'success' || needs.destroy.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
