name: Deploy to environment
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      resource-directory:
        required: true
        type: string
      bucket:
        required: true
        type: string
      environment:
        required: true
        type: string
      node-version:
        type: string
        default: 18.x
env:
  PROJECT_NUMBER: ${{ inputs.environment == 'dev' && secrets.GCP_PROJECT_NUMBER_DEV || inputs.environment == 'prod' && secrets.GCP_PROJECT_NUMBER_PROD }}
  PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}-${{ inputs.environment }}
  ENVIRONMENT: ${{ inputs.environment == 'dev' && 'DEV' || inputs.environment == 'prod' && 'PROD' }}
permissions: write-all
jobs:
  deploy:
    name: Deploy application
    environment: ${{ inputs.environment == 'dev' && 'DEV' || inputs.environment == 'prod' && 'PROD' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: devops-app@${{ env.PROJECT_NAME }}.iam.gserviceaccount.com
      - name: Setup Node ${{inputs.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          registry-url: https://npm.pkg.github.com
      - name: Prepare environment
        run: cp environments/${{env.ENVIRONMENT}}.env .env
        working-directory: ${{inputs.path}}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_DEFAULT_ORG_PAT }}
        working-directory: ${{inputs.path}}
      - name: Build
        run: npm run build
        working-directory: ${{inputs.path}}
      - name: Upload to bucket
        run: gcloud storage cp ${{inputs.resource-directory}}/* gs://${{inputs.bucket}}/ --recursive
        working-directory: ${{inputs.path}}
