name: Deploy to GCP - DEV
on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: dev
    secrets:
      GCP_PROJECT_NUMBER_DEV:
        required: true
      GCP_PROJECT_NAME:
        required: true
      GCP_SERVICE_NAME:
        required: true
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/ext-initialization-application-properties.yml
  validation:
    needs: init
    name: Validation
    if: ${{ needs.init.outputs.destroy == 'false' }}
    uses: ./.github/workflows/ext-gcp-terraform-validation.yml
  deploy:
    needs: validation
    name: Deploy
    uses: ./.github/workflows/ext-gcp-terraform-deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
  destroy:
    needs: init
    name: Destroy
    if: ${{ needs.init.outputs.destroy != 'false' }}
    uses: ./.github/workflows/ext-gcp-terraform-destroy.yml
    with:
      environment: ${{ inputs.environment }}
      desstroy: ${{ needs.init.outputs.destroy }}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
  create-pr:
    needs:
      - destroy
      - deploy
    if: always() && ((needs.deploy.result == 'success') || needs.destroy.result == 'success')
    name: Create PR to Main
    uses: ./.github/workflows/ext-create-pull-request-to-main.yml
