name: Validate PR to DEV
on:
  workflow_call:
jobs:
  init:
    name: Initialization
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-initialization-destruction-properties.yml@main
  validation:
    needs: init
    name: Validation
    if: needs.init.outputs.destroy == 'false'
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-terraform-validation.yml@main
  finish:
    needs:
      - init
      - validation
    if: always() && (needs.init.outputs.destroy != 'false' || (needs.init.outputs.destroy == 'false' && needs.validation.result == 'success'))
    name: Finish
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-commit-status-check.yml@main
    with:
      sha: ${{github.event.pull_request.head.sha}}
      state: success
      context: Finish Pull Request Validation
      description: Successful
