name: Deploy to GCP - PROD
on:
  workflow_call:
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/ext-initialization-destruction-properties.yml
  deploy:
    needs: init
    if: needs.init.outputs.destroy == 'false'
    name: Deploy
    uses: ./.github/workflows/ext-gcp-terraform-deploy.yml
    with:
      environment: prod
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_PROD }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      aiven-api-token: ${{ secrets.AIVEN_API_TOKEN_PROD }}
  destroy:
    needs: init
    name: Destroy
    if: needs.init.outputs.destroy != 'false'
    uses: ./.github/workflows/ext-gcp-terraform-destroy.yml
    with:
      environment: prod
      destroy: ${{ needs.init.outputs.destroy }}
    secrets:
      project-number: ${{ secrets.GCP_PROJECT_NUMBER_PROD }}
      project-name: ${{ secrets.GCP_PROJECT_NAME }}
      service-name: ${{ secrets.GCP_SERVICE_NAME }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      aiven-api-token: ${{ secrets.AIVEN_API_TOKEN_PROD }}
  create-tag:
    needs:
      - destroy
      - deploy
    if: always() && needs.deploy.result == 'success'
    name: Create tag
    uses: ./.github/workflows/ext-create-tag.yml
    secrets: inherit
  finish:
    needs:
      - deploy
      - destroy
      - create-tag
    if: always() && (needs.deploy.result == 'success' || needs.destroy.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
