name: Prepare feature
on:
  workflow_call:
jobs:
  create-pr:
    name: Create PR to DEV
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-pull-request.yml@main
    with:
      base: develop
      head: ${{github.ref_name}}
      labels: development
      environment: DEV
    secrets: inherit
