name: Create tag
on:
  workflow_call: 
jobs:
  deploy:
    name: Deploy to PROD
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - run: echo "⏳ Implantando em PROD..."
  create-tag:
    needs: deploy
    name: Create tag
    uses: ./.github/workflows/ext-create-tag.yml
    secrets: inherit
