name: Validate PR to PROD
on:
  workflow_call:
jobs:
  origin-validation:
    name: Origin validation
    if: ${{github.head_ref == 'develop'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "⏳ Validação da origem das alterações..."
  unit-tests:
    needs: origin-validation
    name: Unit tests
    uses: ./.github/workflows/ext-spring-maven-unit-test.yml
    with:
      minimum-coverage: 60
  mutation-tests:
    needs: origin-validation
    name: Mutation tests
    uses: ./.github/workflows/ext-spring-maven-mutation-test.yml
    with:
      minimum-coverage: 40
  generate-coverage-summary:
    needs:
      - origin-validation
      - unit-tests
      - mutation-tests
    name: Coverage
    uses: ./.github/workflows/ext-tests-generate-coverage-summary.yml
    if: always() && needs.origin-validation.result == 'success'
    with:
      unit-tests-report: ${{needs.unit-tests.outputs.indexes}}
      mutation-tests-report: ${{needs.mutation-tests.outputs.indexes}}
