name: Deploy to GCP - DEV
on:
  workflow_call:
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-initialization-destruction-properties.yml@main
  deploy:
    needs: init
    if: needs.init.outputs.destroy == 'false'
    name: Deploy
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-terraform-deploy.yml@main
    with:
      environment: dev
    secrets: inherit
  destroy:
    needs: init
    name: Destroy
    if: needs.init.outputs.destroy != 'false'
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-terraform-destroy.yml@main
    with:
      environment: dev
      destroy: ${{ needs.init.outputs.destroy }}
    secrets: inherit
  create-pr:
    needs:
      - destroy
      - deploy
    if: always() && (needs.deploy.result == 'success' || needs.destroy.result == 'success')
    name: Create PR to PROD
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-pull-request.yml@main
    with:
      base: main
      head: develop
      labels: production
      environment: PROD
    secrets: inherit
