name: Create tag
on:
  workflow_call: 
jobs:
  create-tag:
    name: Create tag
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-tag.yml@main
    secrets: inherit
