name: Validate PR
on:
  workflow_call:
jobs:
  origin-validation:
    if: github.event.pull_request.base.ref == 'main'
    name: Origin validation
    uses: ./.github/workflows/ext-pull-request-origin-validation.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      expected_origin: develop
  add-non-functional-label:
    runs-on: ubuntu-latest
    name: Add non-functional label to PR
    steps:
      - name: Add non-funcional label to PR
        run: gh pr edit ${{github.event.pull_request.number}} --repo ${{github.repository}} --add-label="non-functional"
        env:
          GH_TOKEN: ${{github.token}}
  finish:
    needs:
      - origin-validation
      - add-non-functional-label
    name: Finish
    if: always()
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-commit-status-check.yml@main
    with:
      sha: ${{github.event.pull_request.head.sha}}
      state: ${{ (github.event.pull_request.base.ref != 'main' || (github.event.pull_request.base.ref == 'main' && needs.origin-validation.result == 'success')) && 'success' || 'failure' }}
      context: Finish Pull Request Validation
      description: ${{ (github.event.pull_request.base.ref != 'main' || (github.event.pull_request.base.ref == 'main' && needs.origin-validation.result == 'success')) && 'Successful' || 'Failed' }}
