name: Deploy maven package to GitHub Repository
on:
  workflow_call:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'correto'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Deploy
        run: |
          mvn --batch-mode deploy \
              -s settings.xml \
              -DaltReleaseDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
              -DaltSnapshotDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
              -Dserver.github.username=${{ secrets.GH_APP_LOGIN }} \
              -Dserver.github.password=${{ steps.generate-app-token.outputs.token }}
