name: Validate PR to DEV
on:
  workflow_call:
jobs:
  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/ext-laravel-unit-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 60
    secrets: inherit
  mutation-tests:
    name: Mutation tests
    uses: ./.github/workflows/ext-laravel-mutation-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 40
    secrets: inherit
  generate-coverage-summary:
    needs:
      - unit-tests
      - mutation-tests
    name: Coverage
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-tests-generate-coverage-summary.yml@main
    if: always()
    with:
      unit-tests-report: ${{needs.unit-tests.outputs.indexes}}
      mutation-tests-report: ${{needs.mutation-tests.outputs.indexes}}
  finish:
    needs: 
      - unit-tests
      - mutation-tests
      - generate-coverage-summary
    name: Finish
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-commit-status-check.yml@main
    with:
      sha: ${{github.event.pull_request.head.sha}}
      state: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'success' || 'failure'}}
      context: Finish Pull Request Validation
      description: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'Successful' || 'Failed'}}
