name: Deploy to GCP - DEV
on:
  workflow_call:
permissions: write-all
jobs:
  process:
    name: Process
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-deploy-or-destroy-cloudrun-develop.yml@main
    secrets: inherit
  integration-tests:
    needs: process
    if: always() && needs.process.outputs.deployed == 'true'
    name: Execute integration tests
    uses: ./.github/workflows/ext-spring-maven-integration-test.yml
    with:
      path: ${{needs.process.outputs.integration-tests-base-path}}
      report-file: ${{needs.process.outputs.integration-tests-report-file}}
      report-format: ${{needs.process.outputs.integration-tests-report-format}}
    secrets: inherit
  create-pr:
    needs:
      - process
      - integration-tests
    if: always() && (needs.integration-tests.result == 'success' || needs.process.outputs.destroyed == 'true')
    name: Create PR to PROD
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-pull-request.yml@main
    with:
      base: main
      head: develop
      labels: production
      environment: PROD
    secrets: inherit
