name: Validate PR to PROD
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: 18.x
jobs:
  origin-validation:
    name: Origin validation
    uses: ./.github/workflows/ext-pull-request-origin-validation.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      expected_origin: develop
  unit-tests:
    needs: origin-validation
    name: Unit tests
    uses: ./.github/workflows/ext-nodejs-unit-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 60
      node-version: ${{inputs.node-version}}
    secrets: inherit
  mutation-tests:
    needs: origin-validation
    name: Mutation tests
    uses: ./.github/workflows/ext-nodejs-mutation-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 40
      node-version: ${{inputs.node-version}}
    secrets: inherit
  generate-coverage-summary:
    needs:
      - origin-validation
      - unit-tests
      - mutation-tests
    name: Coverage
    uses: ./.github/workflows/ext-tests-generate-coverage-summary.yml
    if: always() && needs.origin-validation.result == 'success'
    with:
      unit-tests-report: ${{needs.unit-tests.outputs.indexes}}
      mutation-tests-report: ${{needs.mutation-tests.outputs.indexes}}
  finish:
    needs:
      - unit-tests
      - mutation-tests
      - generate-coverage-summary
    name: Finish
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-commit-status-check.yml@main
    with:
      sha: ${{github.event.pull_request.head.sha}}
      state: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'success' || 'failure'}}
      context: Finish Pull Request Validation
      description: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'Successful' || 'Failed'}}
