name: Validate Pull Request to Maven Package
on:
  workflow_call:
jobs:
  unit-tests:
    name: Test
    uses: ./.github/workflows/ext-spring-maven-unit-test.yml
  mutation-tests:
    name: Test
    uses: ./.github/workflows/ext-spring-maven-mutation-test.yml
  validate-tests:
    needs:
      - unit-tests
      - mutation-tests
    name: Validate tests
    uses: ./.github/workflows/ext-tests-coverage-validation.yml
    if: always()
    with:
      unit-tests-report: ${{needs.unit-tests.outputs.indexes}}
      mutation-tests-report: ${{needs.mutation-tests.outputs.indexes}}
