name: Deploy to DEV
on:
  workflow_call:
jobs:
  deploy:
    name: Deploy to DEV
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "⏳ Implantando em DEV..."
  create-pr:
    needs: deploy
    name: Create PR to PROD
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-pull-request.yml@main
    with:
      base: main
      head: develop
      labels: production
      environment: PROD
    secrets: inherit
