name: Deploy to GCP - DEV
on:
  workflow_call:
permissions: write-all
jobs:
  process:
    name: Process
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-deploy-or-destroy-cloudrun-develop.yml@main
    secrets: inherit
  create-pr:
    needs: process
    name: Create PR to PROD
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-pull-request.yml@main
    with:
      base: main
      head: develop
      labels: production
      environment: PROD
    secrets: inherit
