name: Validate PR to DEV
on:
  workflow_call:
    inputs:
      java-version:
        type: number
        default: 11
jobs:
  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/ext-spring-maven-unit-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 60
      java-version: ${{inputs.java-version}}
    secrets: inherit
  mutation-tests:
    name: Mutation tests
    uses: ./.github/workflows/ext-spring-maven-mutation-test.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      minimum-coverage: 40
      java-version: ${{inputs.java-version}}
    secrets: inherit
  generate-coverage-summary:
    needs:
      - unit-tests
      - mutation-tests
    name: Coverage
    uses: ./.github/workflows/ext-tests-generate-coverage-summary.yml
    if: always()
    with:
      unit-tests-report: ${{needs.unit-tests.outputs.indexes}}
      mutation-tests-report: ${{needs.mutation-tests.outputs.indexes}}
  finish:
    needs: 
      - unit-tests
      - mutation-tests
      - generate-coverage-summary
    name: Finish
    uses: ./.github/workflows/ext-create-commit-status-check.yml
    with:
      sha: ${{github.event.pull_request.head.sha}}
      state: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'success' || 'failure'}}
      context: Finish Pull Request Validation
      description: ${{(needs.unit-tests.result == 'success' && needs.mutation-tests.result == 'success') && 'Successful' || 'Failed'}}
