name: Deploy to GCP - PROD
on:
  workflow_call:
permissions: write-all
jobs:
  process:
    name: Process
    uses: ./.github/workflows/ext-gcp-deploy-or-destroy-cloudrun-develop.yml
    secrets: inherit
