name: Deploy to GCP - DEV
on:
  workflow_call:
    inputs:
      engine:
        type: string
permissions: write-all
jobs:
  process:
    name: Process
    uses: ./.github/workflows/ext-gcp-deploy-or-destroy-cloudrun-develop.yml
    secrets: inherit
  integration-tests:
    needs: process
    if: always() && needs.process.outputs.destroyed != 'true' && needs.process.result == 'success'
    name: Execute integration tests
    uses: ./.github/workflows/ext-laravel-integration-test.yml
    secrets: inherit
  create-pr:
    needs:
      - process
      - integration-tests
    if: always() && (needs.integration-tests.result == 'success' || (needs.process.outputs.destroyed == 'true' && needs.process.result == 'success'))
    name: Create PR to PROD
    uses: ./.github/workflows/ext-create-pull-request.yml
    with:
      base: main
      head: develop
      labels: production
      environment: PROD
    secrets: inherit
