name: Deploy maven package to GitHub Repository
on:
  workflow_call:
    secrets:
      token:
        required: false
      GH_PRECURSORA_DEFAULT_PAT:
        required: false
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false
      - name: Deploy
        run: |
          mvn --batch-mode deploy \
              -s settings.xml \
              -DaltReleaseDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
              -DaltSnapshotDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
              -Dserver.github.username=${{ github.repository_owner }} \
              -Dserver.github.password=${{ secrets.token == '' && secrets.token || secrets.GH_PRECURSORA_DEFAULT_PAT }}
