name: Deploy maven package to GitHub Repository
on:
  workflow_call:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 11
          java-distribution: temurin
          maven-version: 3.8.1
      - name: Deploy
        run: mvn --batch-mode deploy -s settings.xml -Dserver.github.username=${{ secrets.GH_APP_LOGIN }} -Dserver.github.password=${{ steps.generate-app-token.outputs.token }}
