name: Deploy to GCP - PROD
on:
  workflow_call:
permissions: write-all
jobs:
  init:
    name: Initialization
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-initialization-destruction-properties.yml@main
  deploy:
    needs: init
    if: needs.init.outputs.destroy == 'false'
    name: Deploy
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-terraform-deploy.yml@main
    with:
      environment: prod
    secrets: inherit
  destroy:
    needs: init
    name: Destroy
    if: needs.init.outputs.destroy != 'false'
    uses: precursora/is-module-gcp-deploy-actions-extensions/.github/workflows/ext-gcp-terraform-destroy.yml@main
    with:
      environment: prod
      destroy: ${{ needs.init.outputs.destroy }}
    secrets: inherit
  create-tag:
    needs:
      - destroy
      - deploy
    if: always() && needs.deploy.result == 'success'
    name: Create tag
    uses: precursora/is-module-general-deploy-actions-extensions/.github/workflows/ext-create-tag.yml@main
    secrets: inherit
  finish:
    needs:
      - deploy
      - destroy
      - create-tag
    if: always() && (needs.deploy.result == 'success' || needs.destroy.result == 'success')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "⏳ Finalizando deploy..."
